In [20]:
#Q1
import numpy as nump
arr1 = nump.arange(10, 51, 5)
print("Array:", arr1)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)

Array: [10 15 20 25 30 35 40 45 50]
Shape: (9,)
Size: 9
Data Type: int64


In [19]:
#Q2
array = nump.random.randint(1, 101, size=(4, 5))
print("\n Random Matrix:\n", array)
print("Max Value:", array.max(), "at index", nump.unravel_index(array.argmax(), array.shape))
print("Min Value:", array.min(), "at index", nump.unravel_index(array.argmin(), array.shape))


 Random Matrix:
 [[39 44 57 86 18]
 [18  5 20 40  2]
 [71 81 90 67 31]
 [63 74 35 34 33]]
Max Value: 90 at index (np.int64(2), np.int64(2))
Min Value: 2 at index (np.int64(1), np.int64(4))


In [18]:
#Q3
array2 = nump.arange(1, 25).reshape(4, 6)
print("\n Matrix: \n", array2)
print(" 2nd Row: ", array2[1])
print(" 3rd Column: ", array2[:, 2])


 Matrix: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
 2nd Row:  [ 7  8  9 10 11 12]
 3rd Column:  [ 3  9 15 21]


In [7]:
#Q4
array3 = nump.random.randint(0, 51, size=15)
print("\nOriginal Array:", array3)
array3[array3 > 25] = -1
print("Modified Array:", array3)


Original Array: [ 2 45 26 38 23 46  8 26 41  4  7  4 26 50  1]
Modified Array: [ 2 -1 -1 -1 23 -1  8 -1 -1  4  7  4 -1 -1  1]


In [8]:
#Q5
a = nump.array([1, 2, 3, 4, 5])
b = nump.array([10, 20, 30, 40, 50])
print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [9]:
#Q6
array = nump.random.rand(5, 5)
print("\n5x5 Random Floats:\n", array)
print("Mean:", array.mean())
print("Median:", nump.median(array))
print("Variance:", array.var())
print("Standard Deviation:", array.std())


5x5 Random Floats:
 [[0.04683095 0.06763312 0.17345744 0.82423809 0.551971  ]
 [0.50289078 0.00550236 0.86139891 0.99744228 0.31170689]
 [0.74137247 0.3541551  0.99926548 0.45597553 0.48538334]
 [0.97378716 0.49057269 0.18135806 0.46058305 0.2207347 ]
 [0.52869546 0.51070721 0.94211369 0.13339815 0.33535485]]
Mean: 0.48626115100589706
Median: 0.4853833399261376
Variance: 0.09418358937733842
Standard Deviation: 0.30689344955104275


In [10]:
#Q7
A = nump.arange(1, 7).reshape(3, 2)
B = nump.arange(7, 13).reshape(2, 3)
C = A @ B
print("\n Matrix A: \n", A)
print(" Matrix B: \n", B)
print(" A @ B: \n", C)


 Matrix A: 
 [[1 2]
 [3 4]
 [5 6]]
 Matrix B: 
 [[ 7  8  9]
 [10 11 12]]
 A @ B: 
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [16]:
#Q8
array = nump.arange(1, 37).reshape(6, 6)
print("\n Original one : \n", array)
array[1:4, 1:4] = 0
print(" Modified  with new center  = 0: \n", array)


 Original one : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
 Modified  with new center  = 0: 
 [[ 1  2  3  4  5  6]
 [ 7  0  0  0 11 12]
 [13  0  0  0 17 18]
 [19  0  0  0 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [12]:
#Q9
array = nump.array([5, 10, 15, 20, 25])
modified9 = nump.where(array > 15, 99, 0)
print("\n Original Array: ", array)
print( "Modified with nump.where:", modified9)



 Original Array:  [ 5 10 15 20 25]
Modified with np.where: [ 0  0  0 99 99]


In [14]:
#Q9
array = nump.full((4, 4), 10)
subtractor = nump.array([0, 1, 2, 3])
result = array - subtractor
print("\n Array filled with 10: \n", array)
print(" Result after  Subtraction: \n", result)


 Array filled with 10: 
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
 Result after  Subtraction: 
 [[10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]]
